services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

stages:
  - build
  - test
  - docker
  - notify

build-job:
  stage: build
  image: node:latest
  script:
    #- npm install
    #- npm run build
    - echo "build done!"
  artifacts:
    paths:
      - build/

sonarcloud-check:
  stage: test
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner

test-job:
  stage: test
  script:
    - echo "test done!"

docker-job:
  image: docker:latest
  stage: docker
  script:
    - docker build -t bidwise .
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker tag bidwise:latest $DOCKER_USERNAME/bidwise:latest
    - docker push $DOCKER_USERNAME/bidwise:latest

notify-job:
  stage: notify
  image: curlimages/curl:latest
  script:
    - curl -X POST https://itxvppbr5h.execute-api.us-east-1.amazonaws.com/update